// Industry-standard pigment data with realistic RGB values and properties

export const PIGMENT_CATEGORIES = {
  YELLOW_ORANGE: 'Yellow/Orange',
  RED: 'Red',
  PINK_ROSE: 'Pink/Rose',
  VIOLET_PURPLE: 'Violet/Purple',
  BLUE: 'Blue',
  GREEN: 'Green',
  EARTH_TONES: 'Earth Tones',
  BLACK_BROWN: 'Black/Brown',
  GRAY_SILVER: 'Gray/Silver',
  METALLIC: 'Metallic',
  NEON_FLUORESCENT: 'Neon/Fluorescent',
  WHITE_PASTEL: 'White/Pastel',
};

export const PIGMENTS = [
  // YELLOW/ORANGE PIGMENTS
  {
    id: 'oxide-yellow',
    name: 'Oxide Yellow',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 227, g: 190, b: 60 },
    description: 'Iron oxide, warm earthy yellow',
    strength: 0.6, // Medium tinting strength
    opacity: 0.85,
  },
  {
    id: 'cadmium-yellow',
    name: 'Cadmium Yellow',
    code: 'PY35',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 255, g: 215, b: 0 },
    description: 'Bright, clean yellow',
    strength: 0.8, // Strong tinting power
    opacity: 0.95,
  },
  {
    id: 'raw-sienna',
    name: 'Raw Sienna',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 201, g: 133, b: 50 },
    description: 'Natural earth, yellowish-brown',
    strength: 0.5, // Moderate strength
    opacity: 0.7,
  },
  {
    id: 'hansa-yellow',
    name: 'Hansa Yellow',
    code: 'PY73',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 252, g: 232, b: 54 },
    description: 'Cool, lemony yellow',
    strength: 0.75,
    opacity: 0.8,
  },
  {
    id: 'naples-yellow',
    name: 'Naples Yellow',
    code: 'PBr24',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 250, g: 218, b: 94 },
    description: 'Warm, peachy yellow',
    strength: 0.55,
    opacity: 0.85,
  },
  {
    id: 'cadmium-orange',
    name: 'Cadmium Orange',
    code: 'PO20',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 255, g: 124, b: 0 },
    description: 'Vibrant, pure orange',
    strength: 0.8,
    opacity: 0.95,
  },
  {
    id: 'yellow-ochre',
    name: 'Yellow Ochre',
    code: 'PY43',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 204, g: 154, b: 0 },
    description: 'Earthy, golden yellow',
    strength: 0.55,
    opacity: 0.8,
  },
  {
    id: 'lemon-yellow',
    name: 'Lemon Yellow',
    code: 'PY3',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 255, g: 247, b: 0 },
    description: 'Cool, bright lemon',
    strength: 0.7,
    opacity: 0.75,
  },
  {
    id: 'indian-yellow',
    name: 'Indian Yellow',
    code: 'PY150',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 227, g: 168, b: 87 },
    description: 'Warm, golden-orange',
    strength: 0.65,
    opacity: 0.7,
  },
  {
    id: 'tangerine',
    name: 'Tangerine',
    code: 'PO73',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 255, g: 159, b: 64 },
    description: 'Bright, warm orange',
    strength: 0.7,
    opacity: 0.85,
  },
  {
    id: 'gold',
    name: 'Gold Ochre',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.YELLOW_ORANGE,
    rgb: { r: 255, g: 215, b: 0 },
    description: 'Metallic, rich gold',
    strength: 0.6,
    opacity: 0.85,
  },

  // RED PIGMENTS
  {
    id: 'flag-red',
    name: 'Flag Red (Oxide Red)',
    code: 'PR101',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 193, g: 39, b: 45 },
    description: 'Iron oxide, brick red',
    strength: 0.7,
    opacity: 0.9,
  },
  {
    id: 'cadmium-red',
    name: 'Cadmium Red',
    code: 'PR108',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 227, g: 0, b: 34 },
    description: 'Bright, vivid red',
    strength: 0.85,
    opacity: 0.95,
  },
  {
    id: 'burnt-sienna',
    name: 'Burnt Sienna',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 155, g: 59, b: 33 },
    description: 'Reddish-brown earth tone',
    strength: 0.65,
    opacity: 0.75,
  },
  {
    id: 'alizarin-crimson',
    name: 'Alizarin Crimson',
    code: 'PR83',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 139, g: 0, b: 63 },
    description: 'Deep, cool red with blue undertone',
    strength: 0.85,
    opacity: 0.7,
  },
  {
    id: 'quinacridone-red',
    name: 'Quinacridone Red',
    code: 'PR209',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 198, g: 22, b: 75 },
    description: 'Transparent, bluish-red',
    strength: 0.8,
    opacity: 0.65,
  },
  {
    id: 'venetian-red',
    name: 'Venetian Red',
    code: 'PR101',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 165, g: 42, b: 42 },
    description: 'Earthy, brownish-red',
    strength: 0.7,
    opacity: 0.85,
  },
  {
    id: 'vermilion',
    name: 'Vermilion',
    code: 'PR106',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 227, g: 66, b: 52 },
    description: 'Brilliant orange-red',
    strength: 0.85,
    opacity: 0.9,
  },
  {
    id: 'scarlet',
    name: 'Scarlet Red',
    code: 'PR4',
    category: PIGMENT_CATEGORIES.RED,
    rgb: { r: 255, g: 36, b: 0 },
    description: 'Bright, fiery red',
    strength: 0.8,
    opacity: 0.85,
  },

  // PINK/ROSE PIGMENTS
  {
    id: 'rose-pink',
    name: 'Rose Pink',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 255, g: 102, b: 153 },
    description: 'Bright, warm rose',
    strength: 0.65,
    opacity: 0.75,
  },
  {
    id: 'hot-pink',
    name: 'Hot Pink',
    code: 'PR169',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 255, g: 105, b: 180 },
    description: 'Vibrant, electric pink',
    strength: 0.75,
    opacity: 0.8,
  },
  {
    id: 'coral-pink',
    name: 'Coral Pink',
    code: 'PR255',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 248, g: 131, b: 121 },
    description: 'Warm, peachy pink',
    strength: 0.6,
    opacity: 0.7,
  },
  {
    id: 'blush-pink',
    name: 'Blush Pink',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 255, g: 182, b: 193 },
    description: 'Soft, delicate pink',
    strength: 0.4,
    opacity: 0.6,
  },
  {
    id: 'fuchsia',
    name: 'Fuchsia',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 255, g: 0, b: 128 },
    description: 'Bold, vivid pinkish-purple',
    strength: 0.85,
    opacity: 0.85,
  },
  {
    id: 'salmon-pink',
    name: 'Salmon Pink',
    code: 'PR255',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 250, g: 128, b: 114 },
    description: 'Soft, orange-tinted pink',
    strength: 0.55,
    opacity: 0.7,
  },
  {
    id: 'dusty-rose',
    name: 'Dusty Rose',
    code: 'PR83',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 194, g: 134, b: 141 },
    description: 'Muted, vintage pink',
    strength: 0.5,
    opacity: 0.7,
  },
  {
    id: 'magenta',
    name: 'Magenta',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.PINK_ROSE,
    rgb: { r: 255, g: 0, b: 255 },
    description: 'Pure, process magenta',
    strength: 0.9,
    opacity: 0.85,
  },

  // VIOLET/PURPLE PIGMENTS
  {
    id: 'dioxazine-purple',
    name: 'Dioxazine Purple',
    code: 'PV23',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 93, g: 23, b: 127 },
    description: 'Deep, intense violet',
    strength: 0.95,
    opacity: 0.85,
  },
  {
    id: 'quinacridone-magenta',
    name: 'Quinacridone Magenta',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 188, g: 36, b: 107 },
    description: 'Vivid pinkish-purple',
    strength: 0.85,
    opacity: 0.7,
  },
  {
    id: 'cobalt-violet',
    name: 'Cobalt Violet',
    code: 'PV14',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 130, g: 67, b: 153 },
    description: 'True violet, slightly blue',
    strength: 0.65,
    opacity: 0.75,
  },
  {
    id: 'manganese-violet',
    name: 'Manganese Violet',
    code: 'PV16',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 115, g: 79, b: 150 },
    description: 'Soft, muted violet',
    strength: 0.6,
    opacity: 0.8,
  },
  {
    id: 'ultramarine-violet',
    name: 'Ultramarine Violet',
    code: 'PV15',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 75, g: 54, b: 124 },
    description: 'Deep blue-violet',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'mauve',
    name: 'Mauve',
    code: 'PV19',
    category: PIGMENT_CATEGORIES.VIOLET_PURPLE,
    rgb: { r: 153, g: 102, b: 153 },
    description: 'Soft grayish-purple',
    strength: 0.55,
    opacity: 0.75,
  },

  // BLUE PIGMENTS
  {
    id: 'prussian-blue',
    name: 'Prussian Blue',
    code: 'PB27',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 0, g: 49, b: 83 },
    description: 'Deep, dark blue',
    strength: 0.95, // Very strong, powerful pigment
    opacity: 0.9,
  },
  {
    id: 'ultramarine-blue',
    name: 'Ultramarine Blue',
    code: 'PB29',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 18, g: 10, b: 143 },
    description: 'Rich, warm blue',
    strength: 0.75,
    opacity: 0.85,
  },
  {
    id: 'cobalt-blue',
    name: 'Cobalt Blue',
    code: 'PB28',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 0, g: 71, b: 171 },
    description: 'Medium, bright blue',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'cerulean-blue',
    name: 'Cerulean Blue',
    code: 'PB35',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 42, g: 140, b: 186 },
    description: 'Light, sky blue',
    strength: 0.55,
    opacity: 0.75,
  },
  {
    id: 'phthalo-blue',
    name: 'Phthalo Blue',
    code: 'PB15',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 13, g: 27, b: 68 },
    description: 'Intense, cyan-blue',
    strength: 0.95,
    opacity: 0.9,
  },
  {
    id: 'indigo',
    name: 'Indigo',
    code: 'PBk1',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 29, g: 43, b: 83 },
    description: 'Deep blue-black',
    strength: 0.85,
    opacity: 0.85,
  },
  {
    id: 'turquoise',
    name: 'Turquoise Blue',
    code: 'PB36',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 0, g: 199, b: 183 },
    description: 'Bright cyan-green',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'cyan',
    name: 'Cyan (Process Blue)',
    code: 'PB15:3',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 0, g: 183, b: 235 },
    description: 'Pure process cyan',
    strength: 0.8,
    opacity: 0.85,
  },
  {
    id: 'azure-blue',
    name: 'Azure Blue',
    code: 'PB28',
    category: PIGMENT_CATEGORIES.BLUE,
    rgb: { r: 0, g: 127, b: 255 },
    description: 'Bright sky azure',
    strength: 0.65,
    opacity: 0.8,
  },

  // GREEN PIGMENTS
  {
    id: 'oxide-green',
    name: 'Oxide Green',
    code: 'PG17',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 56, g: 94, b: 64 },
    description: 'Chrome oxide, muted green',
    strength: 0.65,
    opacity: 0.85,
  },
  {
    id: 'phthalo-green',
    name: 'Phthalo Green',
    code: 'PG7',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 0, g: 135, b: 81 },
    description: 'Intense, cyan-green',
    strength: 0.9, // Very strong pigment
    opacity: 0.9,
  },
  {
    id: 'viridian',
    name: 'Viridian',
    code: 'PG18',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 64, g: 130, b: 109 },
    description: 'Cool, blue-green',
    strength: 0.7,
    opacity: 0.7,
  },
  {
    id: 'sap-green',
    name: 'Sap Green',
    code: 'PG8',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 48, g: 105, b: 45 },
    description: 'Natural, yellowish-green',
    strength: 0.65,
    opacity: 0.75,
  },
  {
    id: 'hookers-green',
    name: "Hooker's Green",
    code: 'PG36',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 28, g: 86, b: 66 },
    description: 'Deep, dark green',
    strength: 0.75,
    opacity: 0.8,
  },
  {
    id: 'olive-green',
    name: 'Olive Green',
    code: 'PY129',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 107, g: 142, b: 35 },
    description: 'Warm, yellowish-green',
    strength: 0.6,
    opacity: 0.75,
  },
  {
    id: 'emerald-green',
    name: 'Emerald Green',
    code: 'PG18',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 80, g: 200, b: 120 },
    description: 'Bright, jewel-tone green',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'teal',
    name: 'Teal',
    code: 'PG50',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 0, g: 128, b: 128 },
    description: 'Blue-green, cyan tint',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'mint-green',
    name: 'Mint Green',
    code: 'PG7',
    category: PIGMENT_CATEGORIES.GREEN,
    rgb: { r: 152, g: 255, b: 152 },
    description: 'Light, fresh green',
    strength: 0.4,
    opacity: 0.65,
  },

  // EARTH TONES PIGMENTS
  {
    id: 'terracotta',
    name: 'Terracotta',
    code: 'PR102',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 204, g: 102, b: 51 },
    description: 'Warm, clay orange-brown',
    strength: 0.6,
    opacity: 0.8,
  },
  {
    id: 'rust',
    name: 'Rust',
    code: 'PR101',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 183, g: 65, b: 14 },
    description: 'Deep, oxidized red-brown',
    strength: 0.7,
    opacity: 0.85,
  },
  {
    id: 'sand',
    name: 'Sand',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 194, g: 178, b: 128 },
    description: 'Warm, natural beige',
    strength: 0.4,
    opacity: 0.7,
  },
  {
    id: 'taupe',
    name: 'Taupe',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 140, g: 120, b: 100 },
    description: 'Grayish-brown neutral',
    strength: 0.5,
    opacity: 0.75,
  },
  {
    id: 'clay',
    name: 'Clay',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 185, g: 139, b: 98 },
    description: 'Natural earth clay',
    strength: 0.5,
    opacity: 0.75,
  },
  {
    id: 'caramel',
    name: 'Caramel',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 255, g: 209, b: 150 },
    description: 'Warm, golden brown',
    strength: 0.45,
    opacity: 0.7,
  },
  {
    id: 'mahogany',
    name: 'Mahogany',
    code: 'PR101',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 119, g: 47, b: 26 },
    description: 'Rich, reddish-brown wood tone',
    strength: 0.7,
    opacity: 0.85,
  },
  {
    id: 'bronze',
    name: 'Bronze',
    code: 'PBr24',
    category: PIGMENT_CATEGORIES.EARTH_TONES,
    rgb: { r: 205, g: 127, b: 50 },
    description: 'Metallic brown-orange',
    strength: 0.6,
    opacity: 0.8,
  },

  // BLACK/BROWN PIGMENTS
  {
    id: 'carbon-black',
    name: 'Carbon Black',
    code: 'PBk7',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 20, g: 20, b: 20 },
    description: 'Pure black',
    strength: 1.0, // Extremely strong, use sparingly
    opacity: 1.0,
  },
  {
    id: 'raw-umber',
    name: 'Raw Umber',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 115, g: 74, b: 18 },
    description: 'Cool, greenish-brown',
    strength: 0.55,
    opacity: 0.75,
  },
  {
    id: 'burnt-umber',
    name: 'Burnt Umber',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 138, g: 51, b: 36 },
    description: 'Warm, reddish-brown',
    strength: 0.6,
    opacity: 0.8,
  },
  {
    id: 'ivory-black',
    name: 'Ivory Black',
    code: 'PBk9',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 32, g: 32, b: 30 },
    description: 'Warm black with brown undertone',
    strength: 0.95,
    opacity: 0.95,
  },
  {
    id: 'mars-black',
    name: 'Mars Black',
    code: 'PBk11',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 28, g: 28, b: 28 },
    description: 'Neutral, opaque black',
    strength: 0.9,
    opacity: 1.0,
  },
  {
    id: 'van-dyke-brown',
    name: 'Van Dyke Brown',
    code: 'PBr8',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 102, g: 66, b: 40 },
    description: 'Very dark, rich brown',
    strength: 0.75,
    opacity: 0.85,
  },
  {
    id: 'sepia',
    name: 'Sepia',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 112, g: 66, b: 20 },
    description: 'Warm, dark brown',
    strength: 0.7,
    opacity: 0.8,
  },
  {
    id: 'chocolate-brown',
    name: 'Chocolate Brown',
    code: 'PBr6',
    category: PIGMENT_CATEGORIES.BLACK_BROWN,
    rgb: { r: 123, g: 63, b: 0 },
    description: 'Rich, dark chocolate',
    strength: 0.65,
    opacity: 0.85,
  },

  // GRAY/SILVER PIGMENTS
  {
    id: 'charcoal-gray',
    name: 'Charcoal Gray',
    code: 'PBk7',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 54, g: 69, b: 79 },
    description: 'Deep, cool gray',
    strength: 0.7,
    opacity: 0.85,
  },
  {
    id: 'slate-gray',
    name: 'Slate Gray',
    code: 'PBk19',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 112, g: 128, b: 144 },
    description: 'Medium, blue-tinted gray',
    strength: 0.55,
    opacity: 0.75,
  },
  {
    id: 'silver-gray',
    name: 'Silver Gray',
    code: 'PW6',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 192, g: 192, b: 192 },
    description: 'Light, metallic gray',
    strength: 0.4,
    opacity: 0.7,
  },
  {
    id: 'pearl-gray',
    name: 'Pearl Gray',
    code: 'PW6',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 230, g: 228, b: 222 },
    description: 'Warm, elegant light gray',
    strength: 0.3,
    opacity: 0.65,
  },
  {
    id: 'graphite',
    name: 'Graphite',
    code: 'PBk10',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 65, g: 65, b: 65 },
    description: 'Dark, carbon gray',
    strength: 0.8,
    opacity: 0.9,
  },
  {
    id: 'ash-gray',
    name: 'Ash Gray',
    code: 'PBk19',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 178, g: 190, b: 181 },
    description: 'Soft, green-tinted gray',
    strength: 0.35,
    opacity: 0.7,
  },
  {
    id: 'warm-gray',
    name: 'Warm Gray',
    code: 'PBr7',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 147, g: 141, b: 132 },
    description: 'Brown-tinted neutral gray',
    strength: 0.45,
    opacity: 0.7,
  },
  {
    id: 'cool-gray',
    name: 'Cool Gray',
    code: 'PB29',
    category: PIGMENT_CATEGORIES.GRAY_SILVER,
    rgb: { r: 140, g: 146, b: 172 },
    description: 'Blue-tinted neutral gray',
    strength: 0.45,
    opacity: 0.7,
  },

  // METALLIC PIGMENTS
  {
    id: 'metallic-gold',
    name: 'Metallic Gold',
    code: 'PM1',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 212, g: 175, b: 55 },
    description: 'Shimmery gold metallic',
    strength: 0.65,
    opacity: 0.85,
  },
  {
    id: 'metallic-silver',
    name: 'Metallic Silver',
    code: 'PM2',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 192, g: 192, b: 192 },
    description: 'Bright silver metallic',
    strength: 0.55,
    opacity: 0.8,
  },
  {
    id: 'metallic-copper',
    name: 'Metallic Copper',
    code: 'PM3',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 184, g: 115, b: 51 },
    description: 'Warm copper metallic',
    strength: 0.6,
    opacity: 0.8,
  },
  {
    id: 'metallic-bronze',
    name: 'Metallic Bronze',
    code: 'PM4',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 205, g: 127, b: 50 },
    description: 'Rich bronze metallic',
    strength: 0.6,
    opacity: 0.8,
  },
  {
    id: 'metallic-rose-gold',
    name: 'Metallic Rose Gold',
    code: 'PM5',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 183, g: 110, b: 121 },
    description: 'Elegant rose gold metallic',
    strength: 0.5,
    opacity: 0.75,
  },
  {
    id: 'metallic-pearl',
    name: 'Metallic Pearl',
    code: 'PM6',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 240, g: 234, b: 214 },
    description: 'Iridescent pearl white',
    strength: 0.35,
    opacity: 0.65,
  },
  {
    id: 'metallic-champagne',
    name: 'Metallic Champagne',
    code: 'PM7',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 247, g: 231, b: 206 },
    description: 'Soft champagne shimmer',
    strength: 0.4,
    opacity: 0.7,
  },
  {
    id: 'metallic-gunmetal',
    name: 'Metallic Gunmetal',
    code: 'PM8',
    category: PIGMENT_CATEGORIES.METALLIC,
    rgb: { r: 82, g: 87, b: 94 },
    description: 'Dark metallic gray',
    strength: 0.7,
    opacity: 0.85,
  },

  // NEON/FLUORESCENT PIGMENTS
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    code: 'NF1',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 255, g: 20, b: 147 },
    description: 'Bright fluorescent pink',
    strength: 0.9,
    opacity: 0.8,
  },
  {
    id: 'neon-orange',
    name: 'Neon Orange',
    code: 'NF2',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 255, g: 95, b: 31 },
    description: 'Vivid fluorescent orange',
    strength: 0.85,
    opacity: 0.8,
  },
  {
    id: 'neon-yellow',
    name: 'Neon Yellow',
    code: 'NF3',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 255, g: 255, b: 0 },
    description: 'Bright highlighter yellow',
    strength: 0.8,
    opacity: 0.75,
  },
  {
    id: 'neon-green',
    name: 'Neon Green',
    code: 'NF4',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 57, g: 255, b: 20 },
    description: 'Electric fluorescent green',
    strength: 0.85,
    opacity: 0.8,
  },
  {
    id: 'neon-blue',
    name: 'Neon Blue',
    code: 'NF5',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 77, g: 77, b: 255 },
    description: 'Vibrant electric blue',
    strength: 0.8,
    opacity: 0.8,
  },
  {
    id: 'neon-purple',
    name: 'Neon Purple',
    code: 'NF6',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 187, g: 51, b: 255 },
    description: 'Bright fluorescent purple',
    strength: 0.85,
    opacity: 0.8,
  },
  {
    id: 'neon-coral',
    name: 'Neon Coral',
    code: 'NF7',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 255, g: 83, b: 73 },
    description: 'Fluorescent coral red',
    strength: 0.8,
    opacity: 0.75,
  },
  {
    id: 'neon-lime',
    name: 'Neon Lime',
    code: 'NF8',
    category: PIGMENT_CATEGORIES.NEON_FLUORESCENT,
    rgb: { r: 180, g: 255, b: 20 },
    description: 'Bright chartreuse yellow-green',
    strength: 0.75,
    opacity: 0.75,
  },

  // WHITE/PASTEL PIGMENTS
  {
    id: 'zinc-white',
    name: 'Zinc White',
    code: 'PW4',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 252, g: 252, b: 252 },
    description: 'Cool, transparent white',
    strength: 0.3,
    opacity: 0.5,
  },
  {
    id: 'pearl-white',
    name: 'Pearl White',
    code: 'PW6',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 255, g: 253, b: 245 },
    description: 'Warm, pearlescent white',
    strength: 0.25,
    opacity: 0.6,
  },
  {
    id: 'pastel-pink',
    name: 'Pastel Pink',
    code: 'PR122',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 255, g: 182, b: 193 },
    description: 'Soft, light pink',
    strength: 0.35,
    opacity: 0.6,
  },
  {
    id: 'pastel-blue',
    name: 'Pastel Blue',
    code: 'PB15',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 173, g: 216, b: 230 },
    description: 'Soft, sky blue',
    strength: 0.35,
    opacity: 0.6,
  },
  {
    id: 'pastel-lavender',
    name: 'Pastel Lavender',
    code: 'PV23',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 230, g: 190, b: 255 },
    description: 'Soft, light purple',
    strength: 0.35,
    opacity: 0.6,
  },
  {
    id: 'pastel-yellow',
    name: 'Pastel Yellow',
    code: 'PY3',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 253, g: 253, b: 150 },
    description: 'Soft, creamy yellow',
    strength: 0.35,
    opacity: 0.6,
  },
  {
    id: 'cream',
    name: 'Cream',
    code: 'PY42',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 255, g: 253, b: 208 },
    description: 'Warm, off-white cream',
    strength: 0.3,
    opacity: 0.65,
  },
  {
    id: 'ivory',
    name: 'Ivory',
    code: 'PW6',
    category: PIGMENT_CATEGORIES.WHITE_PASTEL,
    rgb: { r: 255, g: 255, b: 240 },
    description: 'Warm, elegant off-white',
    strength: 0.25,
    opacity: 0.6,
  },
];

// Base paint definition
export const WHITE_BASE = {
  id: 'titanium-white',
  name: 'Titanium White (Base A)',
  code: 'PW6',
  rgb: { r: 255, g: 255, b: 255 },
  description: 'High opacity white base paint',
  standardAmount: 1000, // ml (1 liter)
};

// Group pigments by category for easy rendering
export const getPigmentsByCategory = () => {
  const grouped = {};

  Object.values(PIGMENT_CATEGORIES).forEach(category => {
    grouped[category] = PIGMENTS.filter(p => p.category === category);
  });

  return grouped;
};

// Get pigment by ID
export const getPigmentById = (id) => {
  return PIGMENTS.find(p => p.id === id);
};

// Get pigment color as hex
export const rgbToHex = (rgb) => {
  const toHex = (n) => {
    const hex = Math.round(n).toString(16).padStart(2, '0');
    return hex;
  };
  return `#${toHex(rgb.r)}${toHex(rgb.g)}${toHex(rgb.b)}`;
};

// Get pigment color as CSS string
export const rgbToCss = (rgb) => {
  return `rgb(${Math.round(rgb.r)}, ${Math.round(rgb.g)}, ${Math.round(rgb.b)})`;
};

export default PIGMENTS;
